name: ci-deployment
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Create the docker container.
        run: docker build -t nerezo/docker-react -f Dockerfile.dev .

      - name: Run the tests with the coverage report.
        run: docker run -e CI=true nerezo/docker-react npm run test -- --coverage

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
          application_name: docker-react
          environment_name: Docker-env
          existing_bucket_name: elasticbeanstalk-us-east-2-584991124710
          version_label: ${{ github.run_number }}
          deployment_package: deploy.zip
