name: Production Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 15.x, 17.x ]

    steps:
      - uses: actions:checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create the docker container.
        run: docker build -t nerezo/docker-react -f Dockerfile.dev .
      - name: Run the tests with the coverage report.
        run: docker run -e CI=true nerezo/docker-react npm run test -- --coverage
      - name: Build the application on the docker container.
        run: docker run -e CI=true nerezo/docker-react npm run build
      - name: Build the application.
        run: npm run build
      - name: Deploy to S3 
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "build"
